version: "3"
services:
  site:
    command: jekyll serve
    build:
      context: .
    volumes:
      - ${PWD}/docs:/srv/jekyll
      - ${PWD}/Gemfile:/srv/jekyll/Gemfile
      - ${PWD}/Gemfile.lock:/srv/jekyll/Gemfile.lock
      - ${PWD}/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
