
# Syntax highlighting
highlighter: rouge

title: Mobile C++ Tutorials
email: your-email@domain.com
description: Build Cross-Platform iOS and Android Apps using Dropbox's Djinni Tool
theme: jekyll-theme-primer